name: Build docker container and publish to dockerhub

on:
  push:
    branches:
      - main

env:
  REGISTRY: docker.io
  IMAGE_NAME: valorouskarma/proclone-frontend

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images : ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        context: .
        tags: ${{ env.IMAGE_NAME }}:latest
        labels: ${{ steps.meta.output.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
